### ISSUE TITLE
Why not Qhull.jl ?

### ISSUE THREAD

**Issue by blegat** [davidavdav/QHull.jl#8]
I was just wondering, wouldn't the name `Qhull.jl` be more helpful for this package since it is a wrapper for the Qhull library ?

**Comment by davidavdav** [comment]
Your guess is as good as mine.  

I suppose the functionality (convex hull) is more important for the name than the implementation (qhull). 

I used to need the convex hull for computing the convex hull of a [receiver operating curve](https://github.com/davidavdav/ROCAnalysis.jl), but for that particular case I implemented a faster version in Julia natively.

**Comment by blegat** [comment]
Thanks for your reply. I am saying that because there are many tools out there to compute convex hulls/representation conversion for polyhedra/polytopes ([ConvexHull.jl](https://github.com/joehuchette/ConvexHull.jl), [CDD](https://github.com/blegat/CDDLib.jl), [LRS](https://github.com/blegat/LRSLib.jl), Qhull, ...) and I am trying to find suitable way to make it more convenient to use them by providing a common interface and interoperability between them using [Polyhedra.jl](https://github.com/blegat/Polyhedra.jl).

In many cases (like scipy) they decide to choose one library and create a function called e.g. chull or convexhull that computes the convex hull, keeping the name of the library as an implementation detail.
For Julia, I suggest to be more ambitious with [Polyhedra.jl](https://github.com/blegat/Polyhedra.jl) and do something a bit like `MathProgBase` did for solvers.
What do you think ?

If you accept, I will send you a pull request with the necessary code to make it possible to use Qhull through your package using Polyhedra.jl.

**Comment by blegat** [comment]
Thanks a lot and sorry for bothering :)
